### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by mcwimm** [jbathmann/pyMANGA#136]
**Variable assignments**  
Some variable assignments might be prone to error, e.g. in _TimeLoopLib/TreeDynamicTimeLoop.py_
`self.t_ini, self.t_end, self.step_on, self.update_ag, self.update_bg, self.update_gd = self.loop.getNextTimeStep()`

**If-conditions**  
Change `if args.find("n_step_bg")` to `if args.find("n_step_bg") is not None:`

**Comment by jbathmann** [comment]
Grep didn't show any if conditions which can be related to your suggestion except those which are already updated

**Comment by mcwimm** [comment]
> Grep didn't show any if conditions which can be related to your suggestion except those which are already updated

Perfect. What about the other issue?

**Comment by jbathmann** [comment]
Closed with #141, #138 and #134
