### ISSUE TITLE
Container Version of OGS

### ISSUE THREAD

**Issue by jbathmann** [jbathmann/pyMANGA#151]
For those using ogs on ubuntu, the workaround will be to create use a singularity container.
Here I would like to collect the required packages added to this container. 

So @mcwimm, @jvollhueter & @zaphod-bx which python-packages do you need for you ogs-boundary conditions scripts?
Just checking my requirements, i would add "numpy" and "vtk". Do you need anything else?

**Comment by zaphod-bx** [comment]
seems good to me

**Comment by jvollhueter** [comment]
Just for understanding: In this new container then only OGS runs, not whole pyMANGA?

**Comment by mcwimm** [comment]
I also only use vtk and numpy.

**Comment by jbathmann** [comment]
@all thanks for the response.
@jvollhueter singularity containers do not work with windows or macos. What I am preparing atm is a pr, where pymanga uses a singularity container with ogs 6.4.2 installed for linux users & windows users use the respective .exe file from the release-homepage.

**Comment by jbathmann** [comment]
Please have a look at pr #154
