### ISSUE TITLE
Terminal prints during modeling

### ISSUE THREAD

**Issue by jvollhueter** [jbathmann/pyMANGA#152]
The TreeDynamicTimeLoop script prints the start and end time in the terminal. With longer model runtimes these are very large numbers.

I would suggest to either replace or add additionally the output with a percentage indication of which time step is currently being calculated. What do you think?

**Comment by jbathmann** [comment]
As the step is independent of the greater context, i.e. its just 2 timepoints without any context, it is hard to add a progress indication.
However, one could change the output format to scientific numbers in order to improve readability. Additionally, I'd be happy if you make the output optional.

**Comment by mcwimm** [comment]
I like the idea to have the output optional :)
We could also present those outputs in another unit, e.g. years. In most cases, this would be easier to read.

**Comment by jvollhueter** [comment]
Should I just create a pull request and we discuss how to do it exactly there?

**Comment by mcwimm** [comment]
> Should I just create a pull request and we discuss how to do it exactly there?

This would be great :)

**Comment by mcwimm** [comment]
@jvollhueter Can we close the issue?
