### ISSUE TITLE
Webpage Layout

### ISSUE THREAD

**Issue by mcwimm** [jbathmann/pyMANGA#197]
- [x] Unify layout: In some sections the layout changes (e.g. header background color)

![image](https://user-images.githubusercontent.com/48250781/201308042-b7605b70-be8d-4f1f-b436-81db42c4b4ca.png)

- [x] Add main (first) headline of a page to the toc on the right

![image](https://user-images.githubusercontent.com/48250781/201307864-b37beccd-5be3-47ff-b020-2c5398d3fb5b.png)

**Comment by jbathmann** [comment]
Please see #199
