### ISSUE TITLE
Salinity in different bg-concepts

### ISSUE THREAD

**Issue by mcwimm** [jbathmann/pyMANGA#81]
I think porewater salinity is defined in different units in different concepts: in fixedSalinity it is kg/kg and in simpleHydro it's g/kg, right? We might want to agree on one.

**Comment by jbathmann** [comment]
Thanks for the remark. We should stick to one definition here.
As I love SI units I'd vote for ppt
@zaphod-bx and @mcwimm what do you vote for?

**Comment by mcwimm** [comment]
I'm also for ppt. This is more intuitive.

**Comment by jbathmann** [comment]
Ups. I ment, that I'd like kg/kg. E.g. 35 ppt = 0.035

**Comment by mcwimm** [comment]
However, salinity is mostly given in ppt or psu and for mass concentrations g/kg is also common.

**Comment by jbathmann** [comment]
Alright. In OGS, we have to use kg/kg, but that's fine.

**Comment by mcwimm** [comment]
If we have to use it for ogs I'm fine with kg/kg, too. then at least it's consistent.

**Comment by jbathmann** [comment]
Please see PR #83. 
I decided to change from ppt to g/kg as it is less effort. However, I can do it the other way around, if you wish. :-)

**Comment by mcwimm** [comment]
Problem resolved (but ppt to kg/kg)!
